:<h1>
<b>
<font color = 'brown' size = "6">
Convolution in Convolutional Neural Networks
</font>
</b>
</h1>

<h1>
<ul>
<font color = 'brown green' size = '5'>
<b>

<li>
The convolutional neural network, or CNN for short, is a specialized type of neural network model designed for working with two-dimensional image data, although they can be used with one-dimensional and three-dimensional data.
</li><br>

<li>
Central to the convolutional neural network is the convolutional layer that gives the network its name. This layer performs an operation called a convolution.
</li><br>

<li>
In the context of a convolutional neural network, a convolution is a linear operation that involves the multiplication of a set of weights with the input, much like a traditional neural network.
</li><br>

<li>
Given that the technique was designed for two-dimensional input, the multiplication is performed between an array of input data and a two-dimensional array of weights, called a filter or a kernel.
</li><br>

</b>
</font>
</ul>
</h1>

<h1>
<b>
<font color = 'brown'>
Example of 1D Convolutional Layer
</font>
</b>
</h1>

1. Open colab or jupyter file

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D

import numpy as np

2. Define input data

In [ ]:
data = np.asarray([0, 0, 0, 1, 1, 0, 0, 0])
data = data.reshape(1, 8, 1)
data

array([[[0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0]]])

3. create model

In [ ]:
model = Sequential()
model.add(Conv1D(filters = 1, kernel_size = 3, input_shape=(8, 1)))

4. Define a vertical line detector or kernel

In [ ]:
weights = [np.asarray([[[0]], [[1]], [[0]]]), np.asarray([0.0])]
weights

[array([[[0]],
 
        [[1]],
 
        [[0]]]),
 array([0.])]

5. store the weights in the model

In [ ]:
model.set_weights(weights)

6. confirm they were stored

In [ ]:
print(model.get_weights())

[array([[[0.]],

       [[1.]],

       [[0.]]], dtype=float32), array([0.], dtype=float32)]


7. apply filter to input data

In [ ]:
yhat = model.predict(data)
yhat

1/1 [==============================] - 0s 41ms/step


array([[[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.]]], dtype=float32)

<h1>
<b>
<font color = 'brown'>
Example of 2D Convolutional Layer
</font>
</b>
</h1>

1. Import the required library

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

from numpy import asarray
import matplotlib.pyplot as plt

2. Define input data

In [ ]:
data = [[0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0]]

data = asarray(data)
data = data.reshape(1, 8, 8, 1)
data.shape

(1, 8, 8, 1)

3. Create the model

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 1, kernel_size = (3,3), input_shape = (8, 8, 1)))

4. Define a vertical line detector

In [ ]:
detector = [[[[0]],[[1]],[[0]]],
           [[[0]],[[1]],[[0]]],
           [[[0]],[[1]],[[0]]]]

weights = [asarray(detector), asarray([0.0])]

5. store the weights in the model

In [ ]:
model.set_weights(weights)

6. Confirm they were stored

In [ ]:
model.get_weights()

[array([[[[0.]],
 
         [[1.]],
 
         [[0.]]],
 
 
        [[[0.]],
 
         [[1.]],
 
         [[0.]]],
 
 
        [[[0.]],
 
         [[1.]],
 
         [[0.]]]], dtype=float32),
 array([0.], dtype=float32)]

7. Apply filter to input data

In [ ]:
yhat = model.predict(data)

1/1 [==============================] - 0s 109ms/step


8. Print each column in the row

In [ ]:
for r in range(yhat.shape[1]):
# print each column in the row
  print([yhat[0,r,c,0] for c in range(yhat.shape[2])])

[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
[0.0, 0.0, 3.0, 3.0, 0.0, 0.0]
